import { Div, H1, H2, P, Button } from "fluent-html";

/**
 * Example fluent-html component using SwiftUI-style methods
 * The Tailwind extractor will find all the classes generated by these methods
 */

export const ExampleCard = () =>
  Div([
    // Header
    H1("Welcome")
      .textSize("4xl")
      .fontWeight("bold")
      .textColor("gray-900")
      .margin("bottom", "8"),

    // Card
    Div([
      H2("Card Title")
        .textSize("2xl")
        .fontWeight("semibold")
        .textColor("gray-800")
        .margin("bottom", "4"),

      P("This is some card content. The Tailwind extractor will detect all the classes generated by the fluent-html methods.")
        .textColor("gray-600")
        .margin("bottom", "6"),

      // Button
      Button("Click Me")
        .padding("x", "6")
        .padding("y", "3")
        .background("blue-500")
        .textColor("white")
        .rounded("lg")
        .fontWeight("semibold")
        .cursor("pointer")
        .addClass("hover:bg-blue-600 active:scale-95 transition-all duration-200"),
    ])
      .background("white")
      .padding("6")
      .rounded("xl")
      .shadow("lg")
      .border()
      .borderColor("gray-200")
      .w("full")
      .maxW("md"),
  ])
    .flex()
    .flexDirection("col")
    .alignItems("center")
    .justifyContent("center")
    .minH("screen")
    .background("gray-50")
    .padding("8");

/**
 * Classes extracted from above:
 *
 * text-4xl, font-bold, text-gray-900, mb-8,
 * text-2xl, font-semibold, text-gray-800, mb-4,
 * text-gray-600, mb-6,
 * px-6, py-3, bg-blue-500, text-white, rounded-lg, font-semibold, cursor-pointer,
 * hover:bg-blue-600, active:scale-95, transition-all, duration-200,
 * bg-white, p-6, rounded-xl, shadow-lg, border, border-gray-200, w-full, max-w-md,
 * flex, flex-col, items-center, justify-center, min-h-screen, bg-gray-50, p-8
 */
