import { Div, H1, H2, P, Button, Span, Img } from "fluent-html";

/**
 * Example fluent-html component using fluent-styling methods
 * The Tailwind extractor will find all the classes generated by these methods
 */

export const ExampleCard = () =>
  Div(
    // Header
    H1("Welcome")
      .textSize("4xl")
      .fontWeight("bold")
      .textColor("gray-900")
      .margin("bottom", "8"),

    // Card
    Div(
      H2("Card Title")
        .textSize("2xl")
        .fontWeight("semibold")
        .textColor("gray-800")
        .margin("bottom", "4"),

      P("Card content with spacing and dividers.")
        .textColor("gray-600")
        .leading("relaxed")
        .margin("bottom", "6"),

      // Button with variant proxy — v2 feature
      Button("Click Me")
        .padding("x", "6")
        .padding("y", "3")
        .background("blue-500")
        .textColor("white")
        .rounded("lg")
        .fontWeight("semibold")
        .cursor("pointer")
        .transition("colors")
        .duration("200")
        .on("hover", t => t.background("blue-600").scale("105").shadow("lg"))
        .on("focus", t => t.ring("2").ringColor("blue-300").outline("none"))
        .on("disabled", t => t.opacity("50").cursor("not-allowed"))
        .at("md", t => t.padding("x", "8").textSize("lg")),
    )
      .background("white")
      .padding("6")
      .rounded("xl")
      .shadow("lg")
      .border()
      .borderColor("gray-200")
      .w("full")
      .maxW("md")
      .spaceY("4")
      .divideY(),

    // New v2 methods showcase
    Div(
      Span("Status").srOnly(),
      Img().objectFit("cover").aspect("video").rounded("lg"),
    )
      .display("inline-flex")
      .alignSelf("center")
      .grow()
      .shrink("0")
      .colSpan("2")
      .select("none")
      .whitespace("nowrap")
      .animate("pulse")
      .rotate("3")
      .translate("x", "4"),

    // Nested variants — dark mode with hover
    Div(
      P("Dark-aware content")
    )
      .background("white")
      .textColor("gray-900")
      .on("dark", t => t
        .background("gray-900")
        .textColor("white")
        .on("hover", t => t.background("gray-800"))
      )
      .at("md", t => t
        .w("1/2")
        .on("hover", t => t.shadow("lg"))
      ),
  )
    .flex()
    .flexDirection("col")
    .alignItems("center")
    .justifyContent("center")
    .minH("screen")
    .background("gray-50")
    .padding("8")
    .gap("6");

/**
 * Classes extracted from above include:
 *
 * Base: text-4xl, font-bold, text-gray-900, mb-8, text-2xl, font-semibold,
 *   text-gray-800, mb-4, text-gray-600, leading-relaxed, mb-6, px-6, py-3,
 *   bg-blue-500, text-white, rounded-lg, cursor-pointer, transition-colors,
 *   duration-200, bg-white, p-6, rounded-xl, shadow-lg, border, border-gray-200,
 *   w-full, max-w-md, space-y-4, divide-y, inline-flex, self-center, grow,
 *   shrink-0, col-span-2, select-none, whitespace-nowrap, animate-pulse,
 *   rotate-3, translate-x-4, object-cover, aspect-video, sr-only,
 *   flex, flex-col, items-center, justify-center, min-h-screen, bg-gray-50, p-8, gap-6
 *
 * Variants: hover:bg-blue-600, hover:scale-105, hover:shadow-lg,
 *   focus:ring-2, focus:ring-blue-300, focus:outline-none,
 *   disabled:opacity-50, disabled:cursor-not-allowed,
 *   md:px-8, md:text-lg, dark:bg-gray-900, dark:text-white,
 *   dark:hover:bg-gray-800, md:w-1/2, md:hover:shadow-lg
 */
